language: node_js
sudo: false
node_js:
- 'iojs'
- '0.12'
- '0.11'
- '0.10'
- '10'
matrix:
  fast_finish: true
script:
- npm test
after_script: npm install coveralls && cat ./coverage/lcov.info | coveralls